name: Swift 논문 요약 봇 자동 실행

on:
  schedule:
    # 매일 오전 8시 (한국 시간 기준 - UTC+9이므로 23시에 실행)
    - cron: '0 23 * * *'
  
  # 수동 실행도 가능하도록 설정
  workflow_dispatch:

jobs:
  run-paper-summary:
    runs-on: ubuntu-latest
    
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v4
    
    - name: Python 환경 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: 의존성 설치
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: 환경 변수 설정
      run: |
        echo "SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}" >> config.env
        echo "SLACK_CHANNEL=${{ secrets.SLACK_CHANNEL }}" >> config.env
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> config.env
        echo "ARXIV_MAX_RESULTS=10" >> config.env
        echo "ARXIV_SEARCH_TERMS=Swift,iOS,iPhone,iPad,SwiftUI,Objective-C,UIKit,Core Data,WatchOS,tvOS" >> config.env
        echo "DATABASE_PATH=./data/papers.db" >> config.env
        echo "LOG_LEVEL=INFO" >> config.env
        echo "LOG_FILE=./logs/slackbot.log" >> config.env
    
    - name: 필요한 디렉토리 생성
      run: |
        mkdir -p data
        mkdir -p logs
    
    - name: 논문 요약 봇 실행
      run: |
        python -m src.main once
    
    - name: 실행 로그 출력 (디버깅용)
      if: always()
      run: |
        if [ -f ./logs/slackbot.log ]; then
          echo "=== 실행 로그 ==="
          cat ./logs/slackbot.log
        else
          echo "로그 파일을 찾을 수 없습니다."
        fi 